language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm run test:coverage
  - npm run build
after_success:
  - codecov
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
