language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "6"
  - "7"
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:coverage
after_success:
  - codecov
